name: study_buddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # HTTP + env
  http: ^1.2.2
  flutter_dotenv: ^6.0.0
  package_info_plus: ^8.0.0
  cupertino_icons: ^1.0.8

  # --- Firebase (compatible set) ---
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.2
  # add others only if you actually use them:
  # firebase_storage: ^12.3.3
  # firebase_analytics: ^11.3.4

  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/elbee.png
    - assets/building_codes.json
    - .env

  fonts:
    - family: BrittanySignature
      fonts:
        - asset: fonts/MyFont-BrittanySignature.ttf
    - family: SuperLobster
      fonts:
        - asset: fonts/MyFont-SuperLobster.ttf
